apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-ingress
spec:
  rules:
  - host: {{ .Values.catalog.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: catalog-service
            port:
              number: 80
