apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog-app.fullname" . }}
  labels:
    {{- include "catalog-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "catalog-app.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "catalog-app.selectorLabels" . | nindent 12 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
{{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
